[workspace]
members = [
    "crates/util",
    "crates/protocol",
    "crates/storage",
    "crates/broker",
    "crates/fibril",
    "crates/tui-example",
    "benches", "crates/client",
]

resolver = "2"
