[package]
name = "fibril-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
fibril-util = { path = "../util" }
anyhow = "1.0"
async-trait = "0.1"
bytes = "1"
rocksdb = "0.24.0"
thiserror = "2.0"
tokio = { version = "1", features = ["full"] }
